### ISSUE TITLE
Зачем функцию объявлять внутри функции?

### ISSUE THREAD

**Issue by coursar** [Targonkp/Homework4#2]
https://github.com/Targonkp/Homework4/blob/2eebf5925f900aaf24bda08a70266a0012d66a53/src/js/app.js#L19-L22

**Comment by Targonkp** [comment]
Разве нельзя так? Чтобы внутри основной функции сразу выполнить все необходимые действия, а её саму затем "закинуть" в addEventListener .

**Comment by coursar** [comment]
Можно, но зачем? Это запутывает код.
