### ISSUE TITLE
Договаривались, что имён myinput, myinput2 быть не должно

### ISSUE THREAD

**Issue by coursar** [Targonkp/Homework4#4]
https://github.com/Targonkp/Homework4/blob/2eebf5925f900aaf24bda08a70266a0012d66a53/src/js/app.js#L88
https://github.com/Targonkp/Homework4/blob/2eebf5925f900aaf24bda08a70266a0012d66a53/src/js/app.js#L97

**Comment by Targonkp** [comment]
Хорошо.

**Comment by coursar** [comment]
@Targonkp, если сделали issue - закрывайте
