### ISSUE TITLE
Объект добавляется в массив раньше, чем проходят проверки

### ISSUE THREAD

**Issue by coursar** [Targonkp/Homework4#5]
https://github.com/Targonkp/Homework4/blob/2eebf5925f900aaf24bda08a70266a0012d66a53/src/js/app.js#L23-L27

**Comment by Targonkp** [comment]
```
if (isNaN(costEl.value))
    {alert('Введите сумму цифрами')} else {
        parentElem.innerHTML = 'Название продукта: ' + arr[i].name + ', стоимость: ' + arr[i].sum + ';';
        resultEl.appendChild(parentElem);
        console.log(arr[i]);
    }

```
Т.е. после данного отрезка нужно добавить:
 pushObject(); 
 const parentElem = document.createElement('p');

**Comment by coursar** [comment]
1. Сначала проверка, затем pushObject
2. Чем меньше замыканий, тем лучше
